name: Run OpenAI Code on Push or Pull Request

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai

    - name: Run OpenAI code
      run: |
        python script.py
        echo "::set-output name=result::$(cat result.txt)" # Set the result as an output

   name: Comment result
      if: always() # Ensure this step runs even if previous steps fail
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          The result of running the OpenAI code on ${{ github.event_name }} is: ${{ steps.run_openai.outputs.result }}
        token: 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
