name: Code Review Github Action
description: 'Improve your pull requests and code base with AI-assisted code reviews'

outputs:
  results:
    description: 'Code review results (experimental)'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai

    # Other steps for getting common ancestor, preparing excluded files, running git diff, etc.

    - name: Run OpenAI code review
      id: openai
      run: |
        # Your script for running OpenAI code review
        # Example:
        cat diff.txt | python ${{ github.action_path }}/action_code_review.py > review.txt
        echo 'reviewresult<<EOF' >> $GITHUB_OUTPUT
        echo "$(cat review.txt)" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_TOKEN: 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  # Replace with your GitHub token

    # Other steps for handling errors, creating comments, etc.
